<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pendaftaran;
use App\Models\SpmbSet;
use Carbon\Carbon;

class PendaftaranSeeder extends Seeder
{
    public function run(): void
    {
        $reg = SpmbSet::where('kode_jalur', 'REG')->first();
        $prs = SpmbSet::where('kode_jalur', 'PRS')->first();
        $afr = SpmbSet::where('kode_jalur', 'AFR')->first();
        $mts = SpmbSet::where('kode_jalur', 'MTS')->first();

        $data = [
            [
                'no_pendaftaran' => 'SPMB-2026-001',
                'nisn' => '0071234567',
                'nama_lengkap' => 'Ahmad Fauzi',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2011-04-12',
                'nik' => '3171011204110001',
                'no_kk' => '3171011204110002',
                'agama' => 'Islam',
                'alamat' => 'Jl. Kebon Jeruk No. 14, Jakarta Barat',
                'telepon' => '081234567890',
                'email' => 'ahmad.fauzi@gmail.com',
                'asal_sekolah' => 'SMPN 1 Jakarta',
                'npsn_asal' => '20101234',
                'nama_ayah' => 'Bambang Sudarmono',
                'pekerjaan_ayah' => 'Wiraswasta',
                'no_hp_ayah' => '081298765432',
                'nama_ibu' => 'Sri Wahyuni',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'no_hp_ibu' => '081298765433',
                'jalur_id' => $reg ? $reg->id : 1,
                'status' => 'diverifikasi',
                'catatan_verifikasi' => 'Berkas lengkap dan sesuai dengan data fisik.',
                'dokumen' => [
                    'kartu_keluarga' => 'kk_ahmad.pdf',
                    'akta_kelahiran' => 'akta_ahmad.pdf',
                    'rapor' => 'rapor_ahmad.pdf',
                    'pas_foto' => 'foto_ahmad.jpg',
                ],
                'created_at' => Carbon::now()->subDays(1),
            ],
            [
                'no_pendaftaran' => 'SPMB-2026-002',
                'nisn' => '0072345678',
                'nama_lengkap' => 'Siti Nurhaliza',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2011-07-22',
                'nik' => '3273012207110003',
                'no_kk' => '3273012207110004',
                'agama' => 'Islam',
                'alamat' => 'Jl. Dago Asri No. 8, Bandung',
                'telepon' => '081345678901',
                'email' => 'siti.nurhaliza@gmail.com',
                'asal_sekolah' => 'SMP Islam Al-Azhar 1',
                'npsn_asal' => '20102345',
                'nama_ayah' => 'Dr. H. Ahmad Rizal',
                'pekerjaan_ayah' => 'Dosen / PNS',
                'no_hp_ayah' => '081387654321',
                'nama_ibu' => 'Hj. Endang Rahayu',
                'pekerjaan_ibu' => 'PNS',
                'no_hp_ibu' => '081387654322',
                'jalur_id' => $prs ? $prs->id : 2,
                'status' => 'diterima',
                'catatan_verifikasi' => 'Juara 1 Olimpiade Matematika Tingkat Kota.',
                'kelas' => 'X IPA 1',
                'dokumen' => [
                    'kartu_keluarga' => 'kk_siti.pdf',
                    'akta_kelahiran' => 'akta_siti.pdf',
                    'rapor' => 'rapor_siti.pdf',
                    'sertifikat' => 'sertifikat_olimpiade.pdf',
                ],
                'created_at' => Carbon::now()->subDays(2),
            ],
            [
                'no_pendaftaran' => 'SPMB-2026-003',
                'nisn' => '0073456789',
                'nama_lengkap' => 'Budi Santoso',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2011-03-05',
                'nik' => '3374010503110005',
                'no_kk' => '3374010503110006',
                'agama' => 'Islam',
                'alamat' => 'Jl. Pemuda No. 45, Semarang',
                'telepon' => '081456789012',
                'email' => 'budi.santoso@yahoo.com',
                'asal_sekolah' => 'SMPN 5 Semarang',
                'npsn_asal' => '20103456',
                'nama_ayah' => 'Suryono',
                'pekerjaan_ayah' => 'Buruh Harian',
                'no_hp_ayah' => '081476543210',
                'nama_ibu' => 'Sutini',
                'pekerjaan_ibu' => 'Pedagang',
                'no_hp_ibu' => '081476543211',
                'jalur_id' => $afr ? $afr->id : 3,
                'status' => 'menunggu',
                'catatan_verifikasi' => 'Menunggu verifikasi fisik KIP.',
                'dokumen' => [
                    'kartu_keluarga' => 'kk_budi.pdf',
                    'kartu_kip' => 'kip_budi.pdf',
                    'rapor' => 'rapor_budi.pdf',
                ],
                'created_at' => Carbon::now()->subDays(3),
            ],
            [
                'no_pendaftaran' => 'SPMB-2026-004',
                'nisn' => '0074567890',
                'nama_lengkap' => 'Riana Putri',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2011-11-18',
                'nik' => '3578011811110007',
                'no_kk' => '3578011811110008',
                'agama' => 'Katolik',
                'alamat' => 'Jl. Raya Darmo No. 102, Surabaya',
                'telepon' => '081567890123',
                'email' => 'riana.putri@hotmail.com',
                'asal_sekolah' => 'SMP Maria Fidelis',
                'npsn_asal' => '20104567',
                'nama_ayah' => 'Hendrikus Setiawan',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'no_hp_ayah' => '081565432109',
                'nama_ibu' => 'Maria Fransiska',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'no_hp_ibu' => '081565432110',
                'jalur_id' => $reg ? $reg->id : 1,
                'status' => 'ditolak',
                'catatan_verifikasi' => 'Domisili di luar zonasi dan nilai di bawah standar minimum.',
                'dokumen' => [
                    'kartu_keluarga' => 'kk_riana.pdf',
                    'rapor' => 'rapor_riana.pdf',
                ],
                'created_at' => Carbon::now()->subDays(4),
            ],
            [
                'no_pendaftaran' => 'SPMB-2026-005',
                'nisn' => '0075678901',
                'nama_lengkap' => 'Muhammad Rizky',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '2011-09-30',
                'nik' => '3201013009110009',
                'no_kk' => '3201013009110010',
                'agama' => 'Islam',
                'alamat' => 'Jl. Pajajaran No. 12, Bogor',
                'telepon' => '081678901234',
                'email' => 'm.rizky@gmail.com',
                'asal_sekolah' => 'SMPN 2 Bogor',
                'npsn_asal' => '20105678',
                'nama_ayah' => 'Drs. H. Mulyadi',
                'pekerjaan_ayah' => 'PNS Kemendikbud',
                'no_hp_ayah' => '081654321098',
                'nama_ibu' => 'Ratna Dewi',
                'pekerjaan_ibu' => 'Guru',
                'no_hp_ibu' => '081654321099',
                'jalur_id' => $prs ? $prs->id : 2,
                'status' => 'diverifikasi',
                'catatan_verifikasi' => 'Sertifikat Basket Juara 2 Provinsi terverifikasi.',
                'dokumen' => [
                    'kartu_keluarga' => 'kk_rizky.pdf',
                    'sertifikat' => 'sertifikat_basket.pdf',
                    'rapor' => 'rapor_rizky.pdf',
                ],
                'created_at' => Carbon::now()->subDays(4),
            ],
            [
                'no_pendaftaran' => 'SPMB-2026-006',
                'nisn' => '0076789012',
                'nama_lengkap' => 'Clarissa Amalia',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2011-01-15',
                'nik' => '3174011501110011',
                'no_kk' => '3174011501110012',
                'agama' => 'Islam',
                'alamat' => 'Jl. Tebet Barat Dalam No. 3, Jakarta Selatan',
                'telepon' => '081789012345',
                'email' => 'clarissa.a@gmail.com',
                'asal_sekolah' => 'SMP Labschool Jakarta',
                'npsn_asal' => '20106789',
                'nama_ayah' => 'Ir. Faisal Basri',
                'pekerjaan_ayah' => 'Arsitek',
                'no_hp_ayah' => '081743210987',
                'nama_ibu' => 'Novianti',
                'pekerjaan_ibu' => 'Desainer',
                'no_hp_ibu' => '081743210988',
                'jalur_id' => $reg ? $reg->id : 1,
                'status' => 'menunggu',
                'catatan_verifikasi' => null,
                'dokumen' => [
                    'kartu_keluarga' => 'kk_clarissa.pdf',
                    'rapor' => 'rapor_clarissa.pdf',
                ],
                'created_at' => Carbon::now()->subDays(5),
            ],
            [
                'no_pendaftaran' => 'SPMB-2026-007',
                'nisn' => '0077890123',
                'nama_lengkap' => 'Dewa Permana',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Denpasar',
                'tanggal_lahir' => '2011-06-08',
                'nik' => '5171010806110013',
                'no_kk' => '5171010806110014',
                'agama' => 'Hindu',
                'alamat' => 'Jl. Gatot Subroto No. 88, Denpasar',
                'telepon' => '081890123456',
                'email' => 'dewa.permana@gmail.com',
                'asal_sekolah' => 'SMPN 1 Denpasar',
                'npsn_asal' => '20107890',
                'nama_ayah' => 'I Wayan Sudira',
                'pekerjaan_ayah' => 'TNI / Polri',
                'no_hp_ayah' => '081832109876',
                'nama_ibu' => 'Ni Made Rai',
                'pekerjaan_ibu' => 'PNS',
                'no_hp_ibu' => '081832109877',
                'jalur_id' => $mts ? $mts->id : 4,
                'status' => 'diterima',
                'catatan_verifikasi' => 'SK Mutasi Tugas Orang Tua SK/2026/04 terverifikasi.',
                'kelas' => 'X IPS 1',
                'dokumen' => [
                    'kartu_keluarga' => 'kk_dewa.pdf',
                    'sk_mutasi' => 'sk_mutasi_sudira.pdf',
                    'rapor' => 'rapor_dewa.pdf',
                ],
                'created_at' => Carbon::now()->subDays(6),
            ],
            [
                'no_pendaftaran' => 'SPMB-2026-008',
                'nisn' => '0078901234',
                'nama_lengkap' => 'Eka Rahmawati',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2011-10-25',
                'nik' => '3471012510110015',
                'no_kk' => '3471012510110016',
                'agama' => 'Islam',
                'alamat' => 'Jl. Malioboro No. 17, Yogyakarta',
                'telepon' => '081901234567',
                'email' => 'eka.rahma@gmail.com',
                'asal_sekolah' => 'SMPN 3 Yogyakarta',
                'npsn_asal' => '20108901',
                'nama_ayah' => 'Agus Priyanto',
                'pekerjaan_ayah' => 'PNS',
                'no_hp_ayah' => '081921098765',
                'nama_ibu' => 'Tri Hastuti',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'no_hp_ibu' => '081921098766',
                'jalur_id' => $reg ? $reg->id : 1,
                'status' => 'diverifikasi',
                'catatan_verifikasi' => 'Berkas telah lengkap.',
                'dokumen' => [
                    'kartu_keluarga' => 'kk_eka.pdf',
                    'rapor' => 'rapor_eka.pdf',
                ],
                'created_at' => Carbon::now()->subDays(6),
            ]
        ];

        foreach ($data as $p) {
            Pendaftaran::updateOrCreate(['no_pendaftaran' => $p['no_pendaftaran']], $p);
        }
    }
}
